// Legal feasibility (City of Pittsburgh), from the research session's files in
// inputs/legal-feasibility/ (see its README.md and senior-and-group-housing.md).
// - Zoning use table §911.02: permission pathway per district × housing type,
//   written as a small typed lookup the map colors zoning polygons with.
// - Senior, care and supportive housing that exists today (facility-level public
//   data; operator contacts already dropped upstream).

import path from "node:path";

import { writeOverlay, type GeoJSONFeature } from "./arcgis";
import { parseCSV } from "./geo";

const DIR = path.resolve(import.meta.dirname, "inputs/legal-feasibility");
const MATRIX_OUT = path.resolve(import.meta.dirname, "../../src/components/map/overlays/legal-matrix.generated.ts");

type Matrix = { as_of: string; source: string; districts: Record<string, Record<string, string>> };

async function buildMatrix() {
  const matrix = (await Bun.file(`${DIR}/typology-district-matrix.json`).json()) as Matrix;
  const pathways = parseCSV(await Bun.file(`${DIR}/pathways.csv`).text());
  const districts = Object.fromEntries(
    Object.entries(matrix.districts).map(([zone, row]) => [zone, { ...row }]),
  );
  const out = `// Generated by scripts/data/legal-feasibility.ts from inputs/legal-feasibility/. Do not edit.

export const LEGAL_MATRIX_AS_OF = ${JSON.stringify(matrix.as_of)};
export const LEGAL_MATRIX_SOURCE = ${JSON.stringify(matrix.source)};

export const PATHWAYS: Record<string, { rank: number; decider: string; hearing: string; clock: string; fee: string; section: string; note: string }> = ${JSON.stringify(
    Object.fromEntries(
      pathways.map((p) => [
        p.pathway,
        { rank: Number(p.rank), decider: p.decider, hearing: p.hearing, clock: p.statutory_clock, fee: p.extra_fee_usd, section: p.section, note: p.note },
      ]),
    ),
    null,
    2,
  )};

export const DISTRICT_PATHWAYS: Record<string, Record<string, string>> = ${JSON.stringify(districts, null, 2)};
`;
  await Bun.write(MATRIX_OUT, out);
  console.log(`legal matrix: ${Object.keys(districts).length} districts, ${pathways.length} pathways`);
}

const KEEP = ["name", "address", "type", "capacity", "capacity_unit", "year", "year_basis", "source", "zon_new", "zoning_use_label", "zoning_use_confidence", "permission_pathway", "multi_unit_pathway", "possible_same_site_as"];

async function buildSeniorHousing() {
  const src = (await Bun.file(`${DIR}/senior-and-group-housing.geojson`).json()) as { features: GeoJSONFeature[] };
  const features = src.features.map((f) => ({
    type: "Feature" as const,
    geometry: f.geometry,
    properties: Object.fromEntries(KEEP.map((k) => [k, f.properties[k] ?? null])),
  }));
  await writeOverlay("senior-supportive-housing.geojson", {
    type: "FeatureCollection",
    features,
    metadata: { source: "research/datasets/legal-feasibility/senior-and-group-housing.geojson (pulled 2026-09-26)", builtAt: new Date().toISOString() },
  });
}

export async function buildLegalFeasibility() {
  await buildMatrix();
  await buildSeniorHousing();
}

if (import.meta.main) await buildLegalFeasibility();
