// Legal feasibility (City of Pittsburgh), from the research session's files in
// inputs/legal-feasibility/ (see its README.md and senior-and-group-housing.md).
// - Zoning use table §911.02: permission pathway per district × housing type,
//   written as a small typed lookup the map colors zoning polygons with.
// - Senior, care and supportive housing that exists today (facility-level public
//   data; operator contacts already dropped upstream).
// - New residential permits 2019–2026 classified by housing type (owner names
//   dropped upstream).
// - City Council land-use actions 2000–2026 from Legistar (rezonings,
//   conditional uses, SP/PUD), geocoded upstream.
// - Zoning Board of Adjustment decisions 2023–2026 (no applicant or owner
//   names were extracted upstream), plus approval counts by district × type.

import path from "node:path";

import { writeOverlay, type GeoJSONFeature } from "./arcgis";
import { parseCSV } from "./geo";

const DIR = path.resolve(import.meta.dirname, "inputs/legal-feasibility");
const MATRIX_OUT = path.resolve(import.meta.dirname, "../../src/components/map/overlays/legal-matrix.generated.ts");

type Matrix = { as_of: string; source: string; districts: Record<string, Record<string, string>> };

async function buildMatrix() {
  const matrix = (await Bun.file(`${DIR}/typology-district-matrix.json`).json()) as Matrix;
  const pathways = parseCSV(await Bun.file(`${DIR}/pathways.csv`).text());
  const districts = Object.fromEntries(
    Object.entries(matrix.districts).map(([zone, row]) => [zone, { ...row }]),
  );
  // Cells read from a special district's own chapter, or still unconfirmed, carry
  // a note explaining the reading; keep it (trimmed) for the tooltip.
  const notes: Record<string, Record<string, { unconfirmed: boolean; note: string }>> = {};
  for (const r of parseCSV(await Bun.file(`${DIR}/typology-district-matrix.csv`).text())) {
    if (r.confidence === "read" || !r.note) continue;
    const note = r.note.length > 240 ? `${r.note.slice(0, 237).trimEnd()}…` : r.note;
    (notes[r.zon_new] ??= {})[r.typology] = { unconfirmed: r.confidence === "unconfirmed", note };
  }
  const zba: Record<string, Record<string, { n: number; approved: number; denied: number; split: number }>> = {};
  // ZBA rows are keyed by base district. Skip a base whose subdistricts have
  // different use rules (e.g. RIV-GI bars housing, RIV-MU allows apartments),
  // since a pooled count would describe none of them.
  const baseOf = (zone: string) => (zone === "R-MU" ? zone : zone.split("-")[0]);
  const mixedBases = new Set<string>();
  const byBase = new Map<string, Record<string, string>[]>();
  for (const [zone, row] of Object.entries(matrix.districts)) byBase.set(baseOf(zone), [...(byBase.get(baseOf(zone)) ?? []), row]);
  for (const [base, rows] of byBase) {
    const keys = Object.keys(rows[0]).filter((k) => k !== "full_zoning_type");
    if (keys.some((k) => new Set(rows.map((r) => r[k])).size > 1)) mixedBases.add(base);
  }
  for (const r of parseCSV(await Bun.file(`${DIR}/zba-outcomes-by-district-typology.csv`).text())) {
    if (r.zon_base === "ALL" || r.relief_type !== "ALL" || r.housing_scope !== "ALL" || r.small_n_flag) continue;
    if (mixedBases.has(r.zon_base)) continue;
    (zba[r.zon_base] ??= {})[r.typology] = { n: Number(r.n), approved: Number(r.approved), denied: Number(r.denied), split: Number(r.split) };
  }
  const out = `// Generated by scripts/data/legal-feasibility.ts from inputs/legal-feasibility/. Do not edit.

export const LEGAL_MATRIX_AS_OF = ${JSON.stringify(matrix.as_of)};
export const LEGAL_MATRIX_SOURCE = ${JSON.stringify(matrix.source)};

export const PATHWAYS: Record<string, { rank: number; decider: string; hearing: string; clock: string; fee: string; section: string; note: string }> = ${JSON.stringify(
    Object.fromEntries(
      pathways.map((p) => [
        p.pathway,
        { rank: Number(p.rank), decider: p.decider, hearing: p.hearing, clock: p.statutory_clock, fee: p.extra_fee_usd, section: p.section, note: p.note },
      ]),
    ),
    null,
    2,
  )};

export const DISTRICT_PATHWAYS: Record<string, Record<string, string>> = ${JSON.stringify(districts, null, 2)};

export const CELL_NOTES: Record<string, Record<string, { unconfirmed: boolean; note: string }>> = ${JSON.stringify(notes, null, 2)};

// ZBA decisions 2023–2026 by base district × project type (all relief types),
// only where the research team didn't flag the sample as too small.
export const ZBA_OUTCOMES: Record<string, Record<string, { n: number; approved: number; denied: number; split: number }>> = ${JSON.stringify(zba, null, 2)};
`;
  await Bun.write(MATRIX_OUT, out);
  console.log(`ZBA counts skipped for mixed-rule bases: ${[...mixedBases].sort().join(", ")}`);
  const noteCount = Object.values(notes).reduce((s, n) => s + Object.keys(n).length, 0);
  console.log(`legal matrix: ${Object.keys(districts).length} districts, ${pathways.length} pathways, ${noteCount} cell notes`);
}

const KEEP = ["name", "address", "type", "capacity", "capacity_unit", "year", "year_basis", "source", "zon_new", "zoning_use_label", "zoning_use_confidence", "permission_pathway", "multi_unit_pathway", "possible_same_site_as"];

async function buildSeniorHousing() {
  const src = (await Bun.file(`${DIR}/senior-and-group-housing.geojson`).json()) as { features: GeoJSONFeature[] };
  // The points were coded against an earlier matrix; recompute both pathways
  // from the current one so this layer agrees with the legal pathway map.
  const matrix = ((await Bun.file(`${DIR}/typology-district-matrix.json`).json()) as Matrix).districts;
  const features = src.features.map((f) => {
    const properties: Record<string, unknown> = Object.fromEntries(KEEP.map((k) => [k, f.properties[k] ?? null]));
    const row = matrix[String(f.properties.zon_new)];
    const uses = String(f.properties.zoning_use_inferred ?? "").split("|").filter(Boolean);
    if (row) {
      properties.multi_unit_pathway = row.multi_unit ?? "unknown";
      if (uses.length) properties.permission_pathway = [...new Set(uses.map((u) => row[u] ?? "unknown"))].join("|");
    }
    return { type: "Feature" as const, geometry: f.geometry, properties };
  });
  await writeOverlay("senior-supportive-housing.geojson", {
    type: "FeatureCollection",
    features,
    metadata: { source: "research/datasets/legal-feasibility/senior-and-group-housing.geojson (pulled 2026-09-26)", builtAt: new Date().toISOString() },
  });
}

const PERMIT_KEEP = ["permit_id", "address", "issue_date", "completed_date", "status", "typology", "units", "classification_confidence", "zon_new", "neighborhood", "days_to_issue", "days_elapsed_if_open", "censored", "same_parcel_n"];

async function buildPermitsByType() {
  const src = (await Bun.file(`${DIR}/permits-new-residential.geojson`).json()) as { features: GeoJSONFeature[] };
  const features = src.features.map((f) => ({
    type: "Feature" as const,
    geometry: f.geometry,
    properties: {
      ...Object.fromEntries(PERMIT_KEEP.map((k) => [k, f.properties[k] ?? null])),
      work_desc: f.properties.work_desc ? String(f.properties.work_desc).slice(0, 160) : null,
    },
  }));
  await writeOverlay("permits-by-type.geojson", {
    type: "FeatureCollection",
    features,
    metadata: { source: "research/datasets/legal-feasibility/permits-new-residential.geojson (pulled 2026-09-26)", builtAt: new Date().toISOString() },
  });
}

const COUNCIL_KEEP = ["file_number", "action_category", "action_subtype", "residential_relevance", "status", "final_action", "final_action_date", "days_intro_to_final", "passed_pursuant_to_case_law", "from_districts", "to_districts", "cu_district_zoned", "housing_typology", "units_stated", "votes_aye", "votes_nay", "legistar_web_url"];

async function buildCouncilActions() {
  const src = (await Bun.file(`${DIR}/council-land-use-actions.geojson`).json()) as { features: GeoJSONFeature[] };
  const blankToNull = (v: unknown) => (v === "" || v == null ? null : v);
  const features = src.features.map((f) => ({
    type: "Feature" as const,
    geometry: f.geometry,
    properties: {
      ...Object.fromEntries(COUNCIL_KEEP.map((k) => [k, blankToNull(f.properties[k])])),
      title: f.properties.title ? String(f.properties.title).slice(0, 220) : null,
      passed_pursuant_to_case_law: f.properties.passed_pursuant_to_case_law === "True",
    },
  }));
  await writeOverlay("council-land-use-actions.geojson", {
    type: "FeatureCollection",
    features,
    metadata: { source: "research/datasets/legal-feasibility/council-land-use-actions.geojson (Legistar, pulled 2026-09-26)", builtAt: new Date().toISOString() },
  });
}

const ZBA_KEEP = ["zone_case", "year", "decision_date", "days_hearing_to_decision", "address", "zon_new", "neighborhood", "housing_scope", "typology", "units_before", "units_after", "units_added", "relief_type", "outcome", "outcome_group", "decision_pdf"];

async function buildZbaDecisions() {
  const src = (await Bun.file(`${DIR}/zba-decisions.geojson`).json()) as { features: GeoJSONFeature[] };
  const blankToNull = (v: unknown) => (v === "" || v == null ? null : v);
  const features = src.features.map((f) => ({
    type: "Feature" as const,
    geometry: f.geometry,
    properties: {
      ...Object.fromEntries(ZBA_KEEP.map((k) => [k, blankToNull(f.properties[k])])),
      is_housing: f.properties.is_housing === "yes",
      request: f.properties.request_as_captioned ? String(f.properties.request_as_captioned).slice(0, 200) : null,
    },
  }));
  await writeOverlay("zba-decisions.geojson", {
    type: "FeatureCollection",
    features,
    metadata: { source: "research/datasets/legal-feasibility/zba-decisions.geojson (pulled 2026-09-26)", builtAt: new Date().toISOString() },
  });
}

export async function buildLegalFeasibility() {
  await buildMatrix();
  await buildSeniorHousing();
  await buildPermitsByType();
  await buildCouncilActions();
  await buildZbaDecisions();
}

if (import.meta.main) await buildLegalFeasibility();
