"""Regenerate research/knowledge/INDEX.md from each node's **One line:** field.

Run from the research/ directory: python3 admin/scripts/build_index.py
"""
import glob
import os
import re

ORDER = ["challenge", "data", "policy", "stakeholders", "methods", "track3", "landscape", "build-plan"]
TITLES = {
    "challenge": "Challenge: what the hackathon asks",
    "data": "Data: endpoints, fields, gotchas",
    "policy": "Policy: zoning rules, approvals, reforms",
    "stakeholders": "Stakeholders: what users say",
    "methods": "Methods: scoring, calibration, LLM",
    "track3": "Track 3: typology, equity, climate",
    "landscape": "Landscape: what already exists",
    "build-plan": "Build plan: architecture, pipeline, timeline",
}

out = [
    "# Index: every node in one line",
    "",
    "*Generated by `admin/scripts/build_index.py` from each node's **One line:** field. Do not hand-edit; re-run the script.*",
    "",
    "Use this to find where a fact lives. Humans: start with [`../BRIEFING.md`](../BRIEFING.md). Agents: grep this file, then open the node; each node lists its sources with verification tags.",
    "",
]
for d in ORDER:
    files = sorted(f for f in glob.glob(f"knowledge/{d}/*.md") if not f.endswith("README.md"))
    if not files:
        continue
    out += [f"## {TITLES[d]}", "", "| Node | What it covers |", "|---|---|"]
    for f in files:
        text = open(f).read()
        m = re.search(r"\*\*One line:\*\*\s*(.+)", text)
        line = m.group(1).strip() if m else "(no one-line summary)"
        warn = " ⚠" if "⚠" in text else ""
        name = os.path.basename(f)[:-3]
        out.append(f"| [{name}]({d}/{os.path.basename(f)}){warn} | {line.replace('|', '/')} |")
    out.append("")
out.append("⚠ = the node contains a correction or warning; read before citing.")
open("knowledge/INDEX.md", "w").write("\n".join(out) + "\n")
print("wrote knowledge/INDEX.md")
