"""Regenerate research/docs/02-bibliography.md from every node's ## Sources section.

Rule: a source's tag is the WEAKEST tag any node gives it (per the 2026-09-26 critique),
because tags are agent-reported. Run from research/: python3 admin/scripts/build_bibliography.py
"""
import glob
import os
import re
from collections import Counter, defaultdict

RANK = {"read": 0, "skimmed": 1, "found": 2, "inaccessible": 3}
src = {}
for f in sorted(glob.glob("knowledge/*/*.md")):
    parts = open(f).read().split("## Sources", 1)
    if len(parts) < 2:
        continue
    for line in parts[1].splitlines():
        if not line.strip().startswith("-"):
            continue
        tags = re.findall(r"`\[(read|skimmed|found|inaccessible)\]`", line)
        links = re.findall(r"\[([^\]]+)\]\((https?://[^)\s]+)\)", line)
        if not tags or not links:
            continue
        for title, url in links:
            url = url.rstrip(".,")
            d = src.setdefault(url, {"title": title, "tags": set(), "nodes": set()})
            d["tags"].update(tags)
            d["nodes"].add(os.path.relpath(f, "knowledge"))


def weakest(tags):
    return max(tags, key=lambda t: RANK[t])


def category(url):
    host = re.sub(r"^https?://", "", url).split("/")[0].lower()
    groups = [
        ("Hackathon materials", ["chatgpt.site", "docs.google"]),
        ("Code of record and City Council", ["ecode360", "legistar"]),
        ("Data services and datasets", ["arcgis", "wprdc", "gisdata.alleghenycounty", "hazards.fema", "nationalmap", "sdmdataaccess", "geodata.epa", "geopub.epa", "fwspublicservices", "tigerweb", "lehd", "rideprt", "zillowstatic", "huduser", "census.gov", "pghbridgis", "realestate.", "gis.dep"]),
        ("Government and agency documents", ["pittsburghpa.gov", "alleghenycounty", "dced.pa.gov", "phfa.org", "ura.org", "pgh2o", "accdpa", "eia.gov", "pghlandbank", "hud.gov"]),
        ("Journalism and press", ["wesa", "publicsource", "post-gazette", "axios", "citizenportal", "wpxi", "keystonenews", "pittsburghquarterly", "govtech", "geekwire", "technical.ly", "njb", "prnewswire", "pcrg", "cityandstateny"]),
        ("Code repositories", ["github.com"]),
        ("Research, academic and policy analysis", ["doi", "journal", "ascelibrary", "wiley", "nationalacademies", "ternercenter", "ternerlabs", "lewis.ucla", "clauswilke", "buildersforclimateaction", "zoningatlas", "sfplanning", "crossworks", "reinvestment", "pewtrusts"]),
    ]
    for name, keys in groups:
        if any(k in host for k in keys):
            return name
    return "Tools, products and documentation"


groups = defaultdict(list)
for url, d in src.items():
    groups[category(url)].append((url, d))
counts = Counter(weakest(d["tags"]) for d in src.values())
conflicts = sum(1 for d in src.values() if len(d["tags"]) > 1)
order = ["Hackathon materials", "Code of record and City Council", "Government and agency documents", "Data services and datasets", "Research, academic and policy analysis", "Journalism and press", "Code repositories", "Tools, products and documentation"]

out = [
    "# Annotated Bibliography",
    "",
    f"**{len(src)} unique external sources**, generated by `admin/scripts/build_bibliography.py` from the Sources section of every knowledge node. Do not hand-edit; re-run the script. Raw evidence: [`../sweeps/`](../sweeps/).",
    "",
    "**Tag rule: the weakest tag any node assigns wins.** Tags are agent-reported, and an earlier strongest-wins rule inflated verification (see the [critique](04-critique.md)). Where nodes disagree, all tags are shown. For blocked sources, see [`../admin/source-access.md`](../admin/source-access.md).",
    "",
    "| Tag (weakest per source) | Count |",
    "|---|---|",
] + [f"| `[{t}]` | {counts.get(t, 0)} |" for t in RANK] + [
    f"| **total** | **{len(src)}** |",
    "",
    f"{conflicts} sources carry conflicting tags across nodes.",
    "",
    "⚠ **Counts describe reach, not reliability.** Most sources are public web pages, GIS endpoints, City/Council records and local journalism, gathered in one day. There are **no practitioner interviews**. Literature recalled from memory has no URL and is listed as `[found]` in [methods/score-design-options](../knowledge/methods/score-design-options.md).",
    "",
    "---",
    "",
]
for g in order:
    if not groups[g]:
        continue
    out += [f"## {g}", "", f"*{len(groups[g])} sources*", ""]
    for url, d in sorted(groups[g], key=lambda x: x[1]["title"].lower()):
        tags = " ".join(f"`[{t}]`" for t in sorted(d["tags"], key=lambda t: -RANK[t]))
        nodes = ", ".join(f"[{n[:-3]}](../knowledge/{n})" for n in sorted(d["nodes"]))
        out.append(f"- [{d['title']}]({url}) {tags} — cited in {nodes}")
    out.append("")
open("docs/02-bibliography.md", "w").write("\n".join(out))
print(len(src), dict(counts), "conflicts:", conflicts)
